// Release build + Playwright required. Uses only a new temporary database and browser context.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const net = require('node:net');
(async () => {
    const root = path.resolve(__dirname, '../..');
    const temporary = await fs.mkdtemp(path.join(os.tmpdir(), 'worklens-draft-browser-'));
    const socket = net.createServer();
    await new Promise(r => socket.listen(0, '127.0.0.1', r));
    const url = `http://127.0.0.1:${socket.address().port}`;
    await new Promise(r => socket.close(r));
    const server = spawn('dotnet', [path.join(root, 'bin/Release/net10.0/WorkLens.dll')], {
        cwd: root, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'],
        env: { ...process.env, ASPNETCORE_URLS: url,
            ConnectionStrings__WorkLens: `Data Source=${path.join(temporary, 'data/worklens.db')}`,
            WorkLens__BackupPath: path.join(temporary, 'backups'), WorkLens__LogPath: path.join(temporary, 'logs') }
    });
    let output = '', browser, debugPage;
    server.stdout.on('data', c => { output += c; }); server.stderr.on('data', c => { output += c; });
    try {
        for (let i = 0; i < 100; i++) {
            if (await fetch(`${url}/healthz`).then(r => r.ok).catch(() => false)) break;
            if (i === 99) throw new Error(output);
            await new Promise(r => setTimeout(r, 200));
        }
        browser = await chromium.launch({ headless: true, channel: process.env.WORKLENS_TEST_BROWSER || 'msedge' });
        const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
        const page = await context.newPage();
        debugPage = page;
        const errors = [];
        page.on('pageerror', e => errors.push(e.message));
        page.on('dialog', d => d.accept());
        const open = async (p, date = '2026-09-07') => {
            await p.goto(`${url}/?date=${date}`);
            await p.locator('.draft-editor fieldset:not([disabled])').waitFor();
        };
        const editor = () => page.locator('.today-quick-add .draft-editor');
        const readyDate = date => page.waitForFunction(expected => {
            const field = document.querySelector('.today-quick-add [data-draft-field="date"]');
            return field?.value === expected && !field.closest('fieldset').disabled;
        }, date);
        const content = async c => c.locator('[data-draft-field="content"]').evaluate(el => window.workLensEasyMde.getValue(el.id));
        const write = async (c, text) => {
            await c.locator('.CodeMirror').click();
            await page.keyboard.press('ControlOrMeta+A'); await page.keyboard.insertText(text);
        };
        const saved = async c => c.locator('[data-draft-status]').filter({ hasText: '草稿已暫存' }).waitFor();
        await open(page);
        const gettingStarted = page.getByRole('dialog', { name: '建立第一份工作摘要', exact: true });
        await gettingStarted.getByRole('button', { name: '略過', exact: true }).click();
        await gettingStarted.waitFor({ state: 'hidden' });
        await editor().locator('[data-draft-field="hours"]').fill('2.5');
        await write(editor(), '跨日期草稿'); await saved(editor());
        await page.getByRole('button', { name: '← 前一天', exact: true }).click();
        await page.waitForURL('**/*date=2026-09-06');
        await readyDate('2026-09-06');
        assert.equal(await content(editor()), '');
        await page.getByRole('button', { name: '後一天 →', exact: true }).click();
        await page.waitForURL('**/*date=2026-09-07');
        await readyDate('2026-09-07');
        assert.equal(await content(editor()), '跨日期草稿');
        await page.reload(); await page.locator('fieldset:not([disabled])').waitFor();
        assert.equal(await content(editor()), '跨日期草稿');
        console.log('PASS date navigation and reload');
        const other = await context.newPage(); await open(other);
        await write(editor(), '此分頁新版'); await saved(editor());
        await other.locator('[data-draft-field="hours"]').fill('4');
        await other.getByRole('alert').filter({ hasText: '其他分頁' }).waitFor();
        assert.equal(await other.locator('[data-draft-field="hours"]').inputValue(), '4');
        other.on('dialog', d => d.accept()); await other.close();
        console.log('PASS conflicting tabs preserve input');
        await editor().getByRole('button', { name: '儲存工作紀錄', exact: true }).evaluate(el => { el.click(); el.click(); });
        await page.locator('#today-records .timeline-item').waitFor();
        assert.equal(await page.locator('#today-records .timeline-item').count(), 1);
        assert.equal(await content(editor()), '');
        assert.equal(await page.evaluate(() => document.activeElement?.dataset.draftField), 'hours');
        console.log('PASS publish, duplicate clicks and focus');
        const modal = page.getByRole('dialog');
        const close = async () => { await modal.getByRole('button', { name: '關閉並保留草稿', exact: true }).last().click(); await modal.waitFor({ state: 'hidden' }); };
        const editWork = () => page.locator('#today-records').getByRole('button', { name: '編輯', exact: true }).click();
        await editWork(); await modal.locator('fieldset:not([disabled])').waitFor();
        assert.equal(await content(modal), '此分頁新版');
        await write(modal, '工作編輯草稿'); await close();
        await editWork(); await modal.locator('fieldset:not([disabled])').waitFor();
        assert.equal(await content(modal), '工作編輯草稿');
        await modal.getByRole('button', { name: '儲存工作紀錄', exact: true }).click(); await modal.waitFor({ state: 'hidden' });
        console.log('PASS work edit recovery');
        const createManual = () => page.getByRole('button', { name: '貼上參考資料', exact: true }).click();
        await createManual(); await modal.locator('fieldset:not([disabled])').waitFor();
        await write(modal, '會議測試草稿'); await close();
        await createManual(); await modal.locator('fieldset:not([disabled])').waitFor();
        assert.equal(await content(modal), '會議測試草稿');
        await modal.getByRole('button', { name: '儲存參考資料', exact: true }).click(); await modal.waitFor({ state: 'hidden' });
        await page.locator('#source-activity > summary').click();
        const editManual = () => page.locator('#source-activity').getByRole('button', { name: '編輯', exact: true }).click();
        await editManual(); await modal.locator('fieldset:not([disabled])').waitFor();
        await write(modal, '會議編輯草稿'); await close();
        await editManual(); await modal.locator('fieldset:not([disabled])').waitFor();
        assert.equal(await content(modal), '會議編輯草稿');
        await modal.getByRole('button', { name: '儲存參考資料', exact: true }).click(); await modal.waitFor({ state: 'hidden' });
        console.log('PASS manual create and edit recovery');
        await editor().locator('[data-draft-field="hours"]').fill('');
        await write(editor(), '驗證失敗保留');
        await editor().getByRole('button', { name: '儲存工作紀錄', exact: true }).click();
        await editor().getByRole('alert').filter({ hasText: '有效時數' }).waitFor();
        assert.equal(await content(editor()), '驗證失敗保留');
        await editor().getByRole('button', { name: '捨棄草稿', exact: true }).click();
        await editor().locator('[data-draft-status]').filter({ hasText: '草稿已捨棄' }).waitFor();
        assert.equal(await content(editor()), '');
        await write(editor(), '複製前輸入');
        await page.locator('#today-records').getByRole('button', { name: '複製', exact: true }).click();
        await saved(editor());
        assert.equal(await content(editor()), '工作編輯草稿');
        await editor().locator('[data-draft-field="date"]').fill('2026-09-09');
        await page.waitForURL('**/*date=2026-09-09');
        await readyDate('2026-09-09');
        assert.equal(await content(editor()), '');
        await editor().locator('[data-draft-field="date"]').fill('2026-09-07');
        await page.waitForURL('**/*date=2026-09-07');
        await readyDate('2026-09-07');
        assert.equal(await content(editor()), '工作編輯草稿');
        await write(editor(), '離頁前最新輸入');
        await page.getByRole('link', { name: '工作摘要', exact: false }).first().click();
        await page.waitForURL('**/reports');
        await open(page);
        assert.equal(await content(editor()), '離頁前最新輸入');
        console.log('PASS validation, discard, copy, date picker and immediate page navigation');
        const producer = await context.newPage(); await open(producer);
        await producer.getByRole('button', { name: '貼上參考資料', exact: true }).click();
        const producerModal = producer.getByRole('dialog');
        await producerModal.locator('fieldset:not([disabled])').waitFor();
        await producerModal.locator('.CodeMirror').click(); await producer.keyboard.insertText('其他分頁匯入');
        await producerModal.getByRole('button', { name: '儲存參考資料', exact: true }).click();
        await producerModal.waitFor({ state: 'hidden' });
        await editor().locator('[data-draft-field="hours"]').focus();
        await page.locator('#source-activity > summary').filter({ hasText: '來源活動（2）' }).waitFor();
        assert.equal(await content(editor()), '離頁前最新輸入');
        assert.equal(await page.evaluate(() => document.activeElement?.dataset.draftField), 'hours');
        await producer.close();
        console.log('PASS periodic source refresh preserves input and focus');
        await write(editor(), '關閉後恢復'); await saved(editor()); await context.close();
        const freshContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
        const fresh = await freshContext.newPage(); await open(fresh);
        assert.equal(await content(fresh.locator('.today-quick-add')), '關閉後恢復');
        assert.ok(await fresh.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        await fs.mkdir(path.join(root, '.test-build'), { recursive: true });
        await fresh.screenshot({ path: path.join(root, '.test-build/drafts-mobile.png'), fullPage: true });
        await fresh.setViewportSize({ width: 1440, height: 1100 });
        await fresh.screenshot({ path: path.join(root, '.test-build/drafts-desktop.png'), fullPage: true });
        console.log('PASS browser close recovery and mobile layout'); await freshContext.close();
        const fallbackContext = await browser.newContext();
        await fallbackContext.route('**/lib/easymde/easymde.min.js', route => route.abort());
        const fallback = await fallbackContext.newPage(); await open(fallback, '2026-09-08');
        await fallback.locator('[data-draft-field="content"]').fill('一般文字草稿');
        await saved(fallback.locator('.draft-editor'));
        await fallback.reload(); await fallback.locator('fieldset:not([disabled])').waitFor();
        assert.equal(await fallback.locator('[data-draft-field="content"]').inputValue(), '一般文字草稿');
        console.log('PASS plain text fallback');
        const longContent = '長篇會議內容測試😀。'.repeat(5000);
        await fallback.locator('[data-draft-field="content"]').fill(longContent);
        await saved(fallback.locator('.draft-editor'));
        await fallback.reload(); await fallback.locator('fieldset:not([disabled])').waitFor();
        assert.equal(await fallback.locator('[data-draft-field="content"]').inputValue(), longContent);
        await fallback.locator('[data-draft-field="hours"]').fill('1');
        await fallback.getByRole('button', { name: '儲存工作紀錄', exact: true }).click();
        await fallback.locator('#today-records .timeline-item').waitFor();
        assert.equal(await fallback.locator('#today-records .timeline-detail').innerText(), longContent);
        console.log('PASS large pasted content survives draft and publication');
        assert.deepEqual(errors, []);
        assert.doesNotMatch(output, /fail:|Unhandled exception/);
    } catch (error) {
        if (debugPage && !debugPage.isClosed()) console.error(await debugPage.locator('.draft-editor').allTextContents());
        console.error(output.slice(-6000));
        throw error;
    } finally {
        if (browser) await browser.close();
        server.kill(); await new Promise(r => server.exitCode !== null ? r() : server.once('exit', r));
        assert.ok(temporary.startsWith(path.join(os.tmpdir(), 'worklens-draft-browser-')));
        await fs.rm(temporary, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
    }
})().catch(e => { console.error(e); process.exitCode = 1; });
